### ISSUE TITLE
Simpler assets (consideration)

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/sassport#1]
Sassport asset management can be greatly simplified by letting the Sass stylesheets themselves manage assets with any plugin. Here's what I'm envisioning:

```js
var sassport = require('sassport');
var sprites = require('sassport-sprites'); // exposes sprites() function

sassport([ sprites ])
  .assets('./assets', 'public/assets')          // assets(localPath, publicPath)
  .render(...);
```

```scss
@import 'sprites'; // imports sassport-sprites module

// This does a few things:
// 1. Grabs PNG images from ./assets/images/*png
// 2. Processes them as a sprite image
// 3. Returns a map of sprites
$sprites: sprites('images/*.png');

@each $sprite, $sprite-meta in $sprites {
  $sprite-name: _($sprite, _split '.', _first);
  $sprite-position: _get($sprite-meta, 'top') _get($sprite-meta, 'left');
  $sprite-width: _get($sprite-meta, 'width');
  $sprite-height: _get($sprite-meta, 'height');

  // etc.
}
```

**PLUGIN:**
```js
var sassport = require('sassport');

module.exports = sassport.module('sprites')
  .function({
    'sprites($path, $opts: null)': sassport.wrap(function(path, opts, done) {
      var path = sassport.assets(path); // getter w/1 argument

      sprites(path, function(res) {
        sassport.saveAsset(res.file); // saves to local assets dir
        done(res.data);
      });
    });
```
